### ISSUE TITLE
Configurer le Code Scanning

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/colisnc-sdk#35]
https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

**Comment by Dougniel** [comment]
@adriens, je. t'affecte le ticket car je n'ai pas d'accès en écriture sur le projet, réaffecté le moi une fois que ce sera bon stp

**Comment by adriens** [comment]
Stratgéie de sécu globale par défaut modifier hier.

**Comment by adriens** [comment]
Ca devrait être bon maintenant

**Comment by Dougniel** [comment]
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/39691264/161004159-be9548c3-fc43-43e4-bf60-23fb1990099c.png">
