### ISSUE TITLE
:rotating_light: Your main branch isn't protected :rotating_light: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-sdk#44]
![image](https://user-images.githubusercontent.com/5235127/178910582-f561ccdc-86b8-4bd3-b5f2-45caf2d3ef30.png)

**Comment by Dougniel** [comment]
@adriens, j'ai pas les droits admin ⬆️

**Comment by adriens** [comment]
Essaie pour voir maintenant :pray:

**Comment by Dougniel** [comment]
> Essaie pour voir maintenant 🙏

C'est bon merci 👍

**Comment by Dougniel** [comment]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/39691264/179468233-5835492a-3c71-4d99-8e3c-7bc8fdaa89e5.png">

**Comment by adriens** [comment]
:rofl:
